### PR TITLE
help page generation

### PR DESCRIPTION
**Pull request by dsavchenko**

### CODE REVIEW

**Comment by dsavchenko** [comment]
Tested with https://github.com/oda-hub/mmoda-frontend-module/pull/209

**Review by volodymyrss — APPROVED** [review]

**Comment by volodymyrss** [comment]
looks good!

image

So this is generated from md by the bot?

**Comment by volodymyrss** [comment]
please let me know when it's deployed, I try with one of mine

**Comment by dsavchenko** [comment]
> please let me know when it's deployed, I try with one of mine

It's already on staging

**Comment by volodymyrss** [comment]
ok, why is my help page not shown https://gitlab.renkulab.io/astronomy/mmoda/grb-detection ?

**Comment by dsavchenko** [comment]
I see it
image

**Comment by volodymyrss** [comment]
Indeed, it was probably older commit still. Cool!
We may wan to add image max width or something

**Comment by dsavchenko** [comment]
> We may wan to add image max width or something

OK, it's good to have. But we can control it globally in css, I think

**Comment by dsavchenko** [comment]
Like this all helpbook images will adapt to the modal window 
```
.node-mmoda-help-page img {
  max-width:100%;
}
```

**Pull request merged**
