### PR TITLE
Build on all branches

### PR DESCRIPTION
**Pull request by volodymyrss**

### CODE REVIEW

**Comment by dsavchenko** [comment]
What is the purpose? 
Probably better to do this for PR (also labeled?)

**Comment by volodymyrss** [comment]
> What is the purpose? Probably better to do this for PR (also labeled?)

Well, the previous one just did not build it on master, only on main, so it was not complete.
This way it will build it for every commit on every branch, including PR. Practically in normal use it would be identical to build on PR and also master.
Why would labelled help? It does not rely on particular labels so there is no change when relabel and no reason to rebuild.

**Comment by volodymyrss** [comment]
> I mean, I'm not sure we really need the container for every push. For example, when we change the galaxy functionality, it will not affect the mmoda deployment (container for galaxy is being built differently)

I am not sure I understand, building container for every push was merged in [there](https://github.com/oda-hub/oda-bot/pull/46) which you approved?

If the package changes, containers which use it should be rebuilt. Or you suggest to have different versions of this package in mmoda and galaxy bot versions?

**Comment by dsavchenko** [comment]
Pushing to master is not so often, it's ok. 
But there is no reason to rebuild the container for mmoda functionality with every push to the branch where I work on galaxy part.

**Comment by volodymyrss** [comment]
> Pushing to master is not so often, it's ok. But there is no reason to rebuild the container for mmoda functionality with every push to the branch where I work on galaxy part.

As long as it is part of this project, the branch will be merged eventually and will end up installed in mmoda bot container too. So it's important that the container build passes, so it functions as a test. If you are making many small commits and do not want to see failures you can exclude it temporarily.

If the galaxy feature is so divergent that it should not be part of the mmoda instance of oda-bot, it can be moved out of this repository. Although I think it's rather related it makes sense that it is part if of.

**Comment by dsavchenko** [comment]
> As long as it is part of this project, the branch will be merged eventually and will end up installed in mmoda bot container too. So it's important that the container build passes, so it functions as a test. If you are making many small commits and do not want to see failures you can exclude it temporarily.

OK, building container as a kind of test makes sense. Temporarily excluding branch could be an option. I will then probably propose the other way around, kind of "no-container" label instead of "build-container" label. Will do in galaxy branch.

**Review by dsavchenko — APPROVED** [review]

**Pull request merged**
